---
title: "mini"
author: "Ziwei Crystal Zang"
date: "11/24/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
#library packages
for (pkg in c("psych", "ggplot2", "dplyr", "data.table", "twitteR", "tidytext", "tidyverse", "rtweet", "mosaic","wordcloud","wordcloud", "RColorBrewer", "wordcloud2")) {
  library(pkg, character.only = TRUE)
}
```

```{r}
tweet_words_clean_ls <- readRDS("~/Documents/2020Fall/2036DS/projects-czang97/tweet_words_clean_ls.rds")
```



# exclude stop words
```{r}
my_stop_words <- stop_words %>% 
  bind_rows(data.frame(word = c("https", "t.co", "rt", "19", "covid", "covid_19","it’s", "2", "1", "i’m", "due", "don’t")))%>% 
  select(-lexicon) 


word_raw <- df%>%
  mutate(date = as.Date(created_at))%>% 
  select(text, date)%>% 
  unnest_tokens(word,text) %>% 
  group_by(date, word)%>%
  summarize(n = n())%>%
  arrange(desc(n))%>%
  anti_join(my_stop_words)

word_c <- tweet_words_clean%>%
  group_by(word)%>%
  summarize(n = sum(n))

tweet_words_clean_ls <- list(word_c, word_raw)

names(tweet_words_clean_ls) <- c("word_c", "word_raw")

#saveRDS(tweet_words_clean_ls, file="tweet_words_clean_ls.rds")
```


```{r}
word_c <- tweet_words_clean_ls$word_c

word_raw <- tweet_words_clean_ls$word_raw

# bigrams <- word_c %>%
#   unnest_tokens(bigram, word, token = "ngrams", n = 2)%>%
#   count(bigram, sort=T) %>%
#   filter(n > 1)
```


# sentiment analysis
```{r}
afinn <- get_sentiments("afinn") #ranking from negative to positive
bing <- get_sentiments("bing") # positive or negative
loughran <- get_sentiments("loughran") #6 sentiments
nrc <- get_sentiments("nrc") #10 sentiment 

#summary
#tb <- as.data.frame(table(nrc$sentiment))
```

# wordclouds
```{r}
set.seed(1)
wordcloud(words = word_c$word, 
          freq = word_c$n, 
          min.freq = 1,  
          max.words=200, random.order=FALSE, rot.per=0.35,           
          colors=brewer.pal(8, "Dark2"),
          scale=c(3.5,0.25))
```

# bing: positive vs negative sentiments
```{r}
sentiment_bing <- word_c %>%
  inner_join(bing)

sentiment_bing %>%
  group_by(sentiment) %>%
  top_n(10, n) %>%
  ungroup() %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(n, word, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sentiment, scales = "free_y") +
  labs(x = "Contribution to sentiment",
       y = NULL)
```

# loughran: 6 sentiments
```{r}
sentiment_loughran <- word_c %>%
  inner_join(loughran)

sentiment_loughran %>%
  group_by(sentiment) %>%
  top_n(10, n) %>%
  ungroup() %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(n, word, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sentiment, scales = "free_y") +
  labs(x = "Contribution to sentiment",
       y = NULL)
```

# nrc: more complex sentiments
```{r}
sentiment_nrc <- word_c%>%
  inner_join(nrc, by = "word")

sentiment_nrc %>%
  group_by(sentiment) %>%
  top_n(10, n) %>%
  ungroup() %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(n, word, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sentiment, scales = "free_y") +
  labs(x = "Contribution to sentiment",
       y = NULL)
```

# affin: sentiments scores
```{r}
sentiment_afinn <- word_c%>%
  inner_join(afinn, by = "word")%>%
  arrange(desc(n))

sentiment_afinn <- sentiment_afinn%>%
 # mutate(rank = seq(1, nrow(sentiment_afinn), by=1))%>%
  mutate(pos = value >= 0)

word_level <- sentiment_afinn$word
sentiment_afinn$word <- factor(sentiment_afinn$word, levels = word_level)

sentiment_afinn%>%
 # top_n(30,n)%>%
ggplot(aes(x = word, y = value, fill=value))+
 # geom_point()  +
  geom_col(position = "identity")+
  theme(legend.position = "right") +
  labs(title = "")+
  theme_minimal()+
  scale_fill_manual(values = c("#CCEEFF", "#FFDDDD"), guide = FALSE)+
  scale_fill_gradient2(midpoint=0, low="blue", mid="white",high="red", space ="Lab" )+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  ylim(-4,4)+
  theme(text = element_text(size=4))
```

#finn by date
```{r fig.height=50}
top <- word_c%>%
  arrange(desc(n))%>%
  top_n(200, n)
top_words <- top$word


word_raw_perc <- word_raw%>%
  group_by(date)%>%
  mutate(sum = sum(n), perc = 100*n/sum)%>%
  select(date, word, perc)

word_raw_perc <- subset(word_raw_perc, word %in% top_words)


sentiment_afinn <- word_raw_perc%>%
  inner_join(afinn, by = "word")%>%
 # arrange(desc(perc))%>%
  group_by(date)%>%
  mutate(pos = if_else(value >= 0, "Positive", "Negative"))

# word_level <- sentiment_afinn$word
# sentiment_afinn$word <- factor(sentiment_afinn$word, levels = word_level)

mplot(sentiment_afinn)

ggplot(data = sentiment_afinn, aes(x = word, y = perc)) +
  geom_point()  + 
  aes(colour = date) + 
  facet_wrap(~pos, ncol = 2, scales = "free_x") + 
  theme(legend.position = "top") +
  labs(title = "")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))


```


