---
title: "bigram"
author: "Ziwei Crystal Zang"
date: "12/1/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Bigrams
```{r eval=FALSE, include=TRUE, message=FALSE, warning=FALSE, paged.print=FALSE}
bigram <- tdf_all%>%
  mutate(date = as.Date(created_at))%>%  
  select(text, date)%>%
  unnest_tokens(bigram, text, token = "ngrams", n = 2)

bigram_count <- bigram%>% 
  group_by(bigram)%>%
  summarize(n = n())%>%
  arrange(desc(n))

bigram_cleaned <- bigram_count%>%
  separate(bigram, c("word1", "word2"), sep = " ")%>%
  filter(!word1 %in% my_stop_words$word) %>%
  filter(!word2 %in% my_stop_words$word)%>%
  unite(bigram, word1, word2, sep = " ")

bigram_cleaned_top <- bigram_cleaned %>%
  top_n(100, n)

head(bigram_cleaned)
saveRDS(bigram_cleaned, file="/Users/czang/Documents/2020Fall/2036DS/projects-czang97/bigram_clean.rds")
```


```{r}
library(igraph)
bigram_df <- readRDS("~/Documents/2020Fall/2036DS/projects-czang97/bigram_clean.rds")

bigram_df_topn <- bigram_df%>%
  filter(n > 1000) 

bigram_separated <- bigram_df_topn%>%
  separate(bigram, c("word1", "word2"), sep = " ")

bigram_graph <- bigram_separated%>%
  graph_from_data_frame()

set.seed(2020)

a <- grid::arrow(type = "closed", length = unit(.15, "inches"))

ggraph(bigram_graph, layout = "fr") +
  geom_edge_link(aes(edge_alpha = n), show.legend = FALSE,
                 arrow = a, end_cap = circle(.03, 'inches')) +
  geom_node_point(size = 5, color = "lightblue") +
  geom_node_text(aes(label = name), vjust = 1, hjust = 1) +
  theme_void()
```



